In [1]:
import pandas as pd
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("mabel.txt",header=None,on_bad_lines='skip',encoding='utf8')

In [3]:
df=df.drop(0)
df.columns=['Date','Chat']
Message=df["Chat"].str.split("-",n=1,expand=True)
df["Time"]=Message[0]
Message1=Message[1].str.split(":",n=1,expand=True)
df["Name"]=Message1[0]
df["Chat"]=Message1[1]
df=df[["Date","Time","Name","Chat"]]
df

,Date,Time,Name,Chat
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K
4,05/12/19,1:42 pm,Mabel Infoziant,Ok
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?
7,05/12/19,1:43 pm,AR❤,Yes Mam
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working
9,05/12/19,1:43 pm,AR❤,Yeah mam
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...
14,05/12/19,1:48 pm,Mabel Infoziant,ok
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts
20,05/12/19,2:06 pm,AR❤,Ok mam
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...
23,05/12/19,4:48 pm,AR❤,Sure mam.
24,05/12/19,8:07 pm,AR❤,Shall I call mam?
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call
26,08/12/19,11:52 pm,AR❤,It's k mam
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached)
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry
31,09/12/19,12:25 pm,AR❤,Can I cal u mam
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...
35,09/12/19,12:28 pm,AR❤,You deleted this message
36,09/12/19,12:29 pm,AR❤,Do the needful
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...
38,09/12/19,12:42 pm,AR❤,Ok mam thank u
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have
41,10/12/19,8:55 am,AR❤,Okay mam
42,12/12/19,2:26 pm,Mabel Infoziant,ok
43,15/12/19,8:22 pm,AR❤,Mam are u free?
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...
46,18/12/19,3:09 pm,AR❤,Hi mam
47,18/12/19,3:09 pm,AR❤,Any updates mam?
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 1 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    50 non-null     object
 1   Time    50 non-null     object
 2   Name    50 non-null     object
 3   Chat    50 non-null     object
dtypes: object(4)
memory usage: 1.7+ KB

In [5]:
#!pip install nltk

In [6]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

In [7]:
dataset=df

In [8]:
dataset.dropna(inplace=True)

In [9]:
import nltk
nltk.download('vader_lexicon')

[nltk_data] Downloading package vader_lexicon to C:\Users\K S
[nltk_data]     MANI\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [10]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer

sid = SentimentIntensityAnalyzer()

In [11]:
senti=sid.polarity_scores(dataset['Chat'][4])

In [12]:
senti

{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.296}

In [13]:
 def sentimentalAnalysis(data,columnname):
        
        #downloading vader_lexicon for the process
        import matplotlib.pyplot as plt
        import seaborn as sns
        "Importing Necessary Packeage"
        from nltk.sentiment.vader import SentimentIntensityAnalyzer
        sid = SentimentIntensityAnalyzer()
        
        "Deleting null pr empty value"
        data.dropna(inplace=True)
        
        "Checking for a comment"
        #sid.polarity_scores(data[columnname][93])
        
        "Creating respective columns"
        
        data['scores'] = data[columnname].apply(lambda commentText: sid.polarity_scores(commentText))
        data['compound']  = data['scores'].apply(lambda score_dict: score_dict['compound'])
        data['Negtive']  = data['scores'].apply(lambda score_dict: score_dict['neg'])
        data['Postive']  = data['scores'].apply(lambda score_dict: score_dict['pos'])
        data['Neutral']  = data['scores'].apply(lambda score_dict: score_dict['neu'])
        
        "Creating final pos or neg using compound score"
        data['comp_score'] = data['compound'].apply(lambda c: 'pos' if c >=0 else 'neg')
        plt.clf()
        #comp=sns.countplot(x = 'comp_score', hue = 'Name', data = data, palette = 'magma')
        #comp.figure.savefig("date_charts.png")
        "Checking how many pos and neg"
        posneg=pd.DataFrame(data['comp_score'].value_counts())
        return posneg,data

In [14]:
pos,data_Senti=sentimentalAnalysis(dataset,columnname='Chat')

In [15]:
data_Senti

,Date,Time,Name,Chat,scores,compound,Negtive,Postive,Neutral,comp_score
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos

In [16]:
pos

            count
comp_score
pos            48
neg             2

In [17]:
# Step 1: Create a 'Flirt' label based on keywords and sentiment
flirty_keywords = ['love', 'baby', 'dear', 'sweet', 'miss', '😍', '😘', '💓', '❤️', 'cute', 'beautiful', 'darling']

def is_flirty(text, comp_score):
    text = str(text).lower()
    if any(word in text for word in flirty_keywords) or comp_score > 0.5:
        return 1  # Flirty
    else:
        return 0  # Not flirty

df['Flirt'] = df.apply(lambda x: is_flirty(x['Chat'], x['compound']), axis=1)
df[['Chat', 'compound', 'Flirt']].head(10)

                                               Chat  compound  Flirt
1                    Hi this is Mabel we just spoke    0.0000      0
2                             What’s your full name    0.0000      0
3                                    Ramisha Rani K    0.0000      0
4                                                Ok    0.2960      0
5                            ramisharanik@gmail.com    0.0000      0
6                                    Your email Id?    0.0000      0
7                                           Yes Mam    0.4019      0
8    I will send 2 abstracts for u to start working    0.0000      0
9                                          Yeah mam    0.2960      0
10                 Give me the list that u have too    0.0000      0

In [21]:
df

,Date,Time,Name,Chat,scores,compound,Negtive,Postive,Neutral,comp_score,Flirt
1,05/12/19,1:42 pm,Mabel Infoziant,Hi this is Mabel we just spoke,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
2,05/12/19,1:42 pm,Mabel Infoziant,What’s your full name,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
3,05/12/19,1:42 pm,AR❤,Ramisha Rani K,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
4,05/12/19,1:42 pm,Mabel Infoziant,Ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,0
5,05/12/19,1:42 pm,Mabel Infoziant,ramisharanik@gmail.com,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
6,05/12/19,1:43 pm,Mabel Infoziant,Your email Id?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
7,05/12/19,1:43 pm,AR❤,Yes Mam,"{'neg': 0.0, 'neu': 0.27, 'pos': 0.73, 'compou...",0.4019,0.000,0.730,0.270,pos,0
8,05/12/19,1:43 pm,Mabel Infoziant,I will send 2 abstracts for u to start working,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
9,05/12/19,1:43 pm,AR❤,Yeah mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,0
10,05/12/19,1:43 pm,Mabel Infoziant,Give me the list that u have too,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
11,05/12/19,1:43 pm,Mabel Infoziant,Send me cbe office address and phone number I...,"{'neg': 0.0, 'neu': 0.915, 'pos': 0.085, 'comp...",0.0772,0.000,0.085,0.915,pos,0
12,05/12/19,1:44 pm,AR❤,Yeah Mam within Evening I will forward you mam.,"{'neg': 0.0, 'neu': 0.761, 'pos': 0.239, 'comp...",0.2960,0.000,0.239,0.761,pos,0
13,05/12/19,1:45 pm,AR❤,Tomorrow I have to visit the office.yet not I...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
14,05/12/19,1:48 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,0
15,05/12/19,1:48 pm,Mabel Infoziant,send the details of office location once u ge...,"{'neg': 0.0, 'neu': 0.896, 'pos': 0.104, 'comp...",0.3612,0.000,0.104,0.896,pos,0
16,05/12/19,1:49 pm,AR❤,Sure mam. Soon I will share details with you mam,"{'neg': 0.0, 'neu': 0.609, 'pos': 0.391, 'comp...",0.5423,0.000,0.391,0.609,pos,1
17,05/12/19,2:00 pm,AR❤,I have read the Abstract mam. We can do mam. ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
18,05/12/19,2:04 pm,Mabel Infoziant,I think Vignesh has the data set will ask him...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
19,05/12/19,2:04 pm,Mabel Infoziant,I have sent the abstracts,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
20,05/12/19,2:06 pm,AR❤,Ok mam,"{'neg': 0.0, 'neu': 0.312, 'pos': 0.688, 'comp...",0.2960,0.000,0.688,0.312,pos,0
21,05/12/19,2:07 pm,AR❤,I have read both the abstract mam. We can do ...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
22,05/12/19,4:44 pm,Mabel Infoziant,Yes we need to ya about amount and all other ...,"{'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'comp...",0.4019,0.000,0.162,0.838,pos,0
23,05/12/19,4:48 pm,AR❤,Sure mam.,"{'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'comp...",0.3182,0.000,0.697,0.303,pos,0
24,05/12/19,8:07 pm,AR❤,Shall I call mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
25,08/12/19,10:45 pm,Mabel Infoziant,Hi I was at church couldn’t take your call,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
26,08/12/19,11:52 pm,AR❤,It's k mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
27,08/12/19,11:55 pm,AR❤,Just to know the tomorrow plan mam.will see t...,"{'neg': 0.0, 'neu': 0.775, 'pos': 0.225, 'comp...",0.4404,0.000,0.225,0.775,pos,0
28,09/12/19,12:09 pm,AR❤,Mam can u send Vignesh number??,"{'neg': 0.0, 'neu': 0.707, 'pos': 0.293, 'comp...",0.1680,0.000,0.293,0.707,pos,0
29,09/12/19,12:13 pm,Mabel Infoziant,Vignesh ML Infoziant.vcf (file attached),"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
30,09/12/19,12:23 pm,Mabel Infoziant,I was in a meeting sorry,"{'neg': 0.302, 'neu': 0.698, 'pos': 0.0, 'comp...",-0.0772,0.302,0.000,0.698,neg,0
31,09/12/19,12:25 pm,AR❤,Can I cal u mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
32,09/12/19,12:26 pm,AR❤,Waiting for u r finalization of rates for our...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
33,09/12/19,12:26 pm,AR❤,If we finiliaze I can work with full involvem...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
34,09/12/19,12:28 pm,AR❤,So what ever may be ..if you think your are c...,"{'neg': 0.0, 'neu': 0.875, 'pos': 0.125, 'comp...",0.5106,0.000,0.125,0.875,pos,1
35,09/12/19,12:28 pm,AR❤,You deleted this message,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
36,09/12/19,12:29 pm,AR❤,Do the needful,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
37,09/12/19,12:41 pm,Mabel Infoziant,No ma please hold I am in a hot meeting with ...,"{'neg': 0.174, 'neu': 0.736, 'pos': 0.089, 'co...",-0.2960,0.174,0.089,0.736,neg,0
38,09/12/19,12:42 pm,AR❤,Ok mam thank u,"{'neg': 0.0, 'neu': 0.175, 'pos': 0.825, 'comp...",0.5719,0.000,0.825,0.175,pos,1
39,10/12/19,7:59 am,Mabel Infoziant,Ramisha we need to talk today i will call u a...,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
40,10/12/19,8:00 am,Mabel Infoziant,Be ready to discuss about the ML titles u have,"{'neg': 0.0, 'neu': 0.762, 'pos': 0.238, 'comp...",0.3612,0.000,0.238,0.762,pos,0
41,10/12/19,8:55 am,AR❤,Okay mam,"{'neg': 0.0, 'neu': 0.345, 'pos': 0.655, 'comp...",0.2263,0.000,0.655,0.345,pos,0
42,12/12/19,2:26 pm,Mabel Infoziant,ok,"{'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound...",0.2960,0.000,1.000,0.000,pos,0
43,15/12/19,8:22 pm,AR❤,Mam are u free?,"{'neg': 0.0, 'neu': 0.377, 'pos': 0.623, 'comp...",0.5106,0.000,0.623,0.377,pos,1
44,15/12/19,8:40 pm,Mabel Infoziant,Am at church can call very late or tomorrow only,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
45,15/12/19,8:40 pm,AR❤,Kk mam. I will ask Arun brother. Small doubt ...,"{'neg': 0.111, 'neu': 0.619, 'pos': 0.27, 'com...",0.5574,0.111,0.270,0.619,pos,1
46,18/12/19,3:09 pm,AR❤,Hi mam,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
47,18/12/19,3:09 pm,AR❤,Any updates mam?,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
48,18/12/19,3:11 pm,Mabel Infoziant,U might have to start on the WhatsApp analysis,"{'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound...",0.0000,0.000,0.000,1.000,pos,0
49,18/12/19,3:11 pm,Mabel Infoziant,There is one project that got committed,"{'neg': 0.0, 'neu': 0.741, 'pos': 0.259, 'comp...",0.2732,0.000,0.259,0.741,pos,0
50,18/12/19,3:12 pm,AR❤,Kk mam👍🏻,"{'neg': 0.0, 'neu': 0.286, 'pos': 0.714, 'comp...",0.3612,0.000,0.714,0.286,pos,0

In [24]:
df['Chat'].value_counts().head(1)

Chat
ok    2
Name: count, dtype: int64

In [25]:
df['Date'] = pd.to_datetime(df['Date'])
df['Date'].value_counts().head(1)

Date
2019-05-12    24
Name: count, dtype: int64

In [32]:
df[df['Name'] == '<Media omitted>']['Chat'].value_counts()

Series([], Name: count, dtype: int64)